# Generated by Django 4.0.4 on 2022-08-04 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chart_title', models.CharField(max_length=500, verbose_name='Title')),
                ('chart_description', models.CharField(max_length=1000)),
                ('chart_url', models.CharField(max_length=512)),
                ('chart_creation_date', models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 38, 5, 484696, tzinfo=utc), verbose_name='Created')),
                ('chart_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_charts.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ChartFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, verbose_name='File subject')),
                ('filename', models.CharField(max_length=20, verbose_name='Filename')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_data_charts.chart')),
            ],
        ),
    ]
