# Generated by Django 4.0.4 on 2022-08-04 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 52, 35, 805214, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='chartfile',
            name='filename',
            field=models.CharField(max_length=100, verbose_name='Filename'),
        ),
    ]
