# Generated by Django 4.0.4 on 2022-08-10 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_charts', '0003_chartsubject_chart_chart_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 9, 19, 13, 255588, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.CreateModel(
            name='ChartMeasure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('measure', models.CharField(max_length=100)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_data_charts.chart')),
            ],
        ),
    ]
