# Generated by Django 4.0.4 on 2022-08-11 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_charts', '0005_chartmeasure_measure_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartmeasure',
            name='measure_label',
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 6, 45, 24, 311106, tzinfo=utc), verbose_name='Created'),
        ),
    ]
