# Generated by Django 4.0.4 on 2022-08-15 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_charts', '0006_remove_chartmeasure_measure_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 10, 32, 2, 50608, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='ChartUrl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_data_charts.chart')),
            ],
        ),
    ]
